import Head from 'next/head';
import Image from 'next/image';

import { dataWorks } from '@/data/dataWorks';

import Hero from '@/components/heros/Hero';
import Products from '@/components/products/Products';
import Solutions from '@/components/solutions/Solutions';
import Works from '@/components/works/Works';
import Faqs from '@/components/faqs/Faqs';
import Emails from '@/components/emails/Emails';
import Customers from '@/components/customers/Customers';

export default function Home({ works }) {
  return (
    <>
      <Head>
        <title>ELS with Sass and Custom Css 01</title>
        <meta name="description" content="ELS Power with Sass and Custom Css Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Products />
      <Solutions />
      <Works works={works} />
      <Customers />
      <Faqs />
      <Emails />
    </>
  )
}


export const getStaticProps = async () => {
  const works = dataWorks;

  return {
    props: { works },
  }
}